from __future__ import annotations

from typing import Any, Callable, Mapping, Protocol

class Entity:
    _attr_has_entity_name: bool | None
    _attr_should_poll: bool | None
    _attr_unique_id: str | None
    _attr_device_info: Mapping[str, Any] | None
    def __init__(self) -> None: ...
    async def async_added_to_hass(self) -> None: ...
    async def async_will_remove_from_hass(self) -> None: ...
    def async_on_remove(self, func: Callable[[], Any]) -> None: ...
    def async_write_ha_state(self) -> None: ...

