from __future__ import annotations

from typing import Any

class QuirkBuilder:
    def __init__(self, manufacturer: str, model: str) -> None: ...
    def replaces(self, cluster_or_device: Any) -> "QuirkBuilder": ...
    def adds(self, cluster: Any) -> "QuirkBuilder": ...
    def add_to_registry(self) -> Any: ...
